version: '3'

services:
  # web:
  #   build:
  #     context: ./web
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./web:/usr/src/app

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./app:/usr/src/app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: