version: '3'

services:
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - app

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./app:/usr/src/app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: