version: '3'

services:
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
    depends_on:
      - app

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./app/src:/usr/src/app/src

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: